#version: '2'

nginx:
        image: nginx
        ports:
                - 80:8080
        links:
                - phpfpm
        volumes:
                - ./logs/access.log:/var/log/nginx/default.access_log
                - ./logs/error.log:/var/log/nginx/default.error_log warn
                - ./nginx-vhost/:/etc/nginx/conf.d/mysite.template
#               - .:/public
#       depends_on:
#               - phpfpm

phpfpm:
        image: php:fpm
        ports:
                - 9000:9000
        volumes:
                - ./public:/usr/share/nginx/html

# mysql:
#        image: bitnami/mariadb:latest
#        ports:
#                - 3306:3306
#        volumes:
#                - ./db-data:/var/lib/mysql:rw
#        environment:
#                - MARIADB_ROOT_PASSWORD=123456
