version: '3'

services:
        nginx:
                image: nginx
                ports:
                        - 80:80
                links:
                        - php
                volumes:
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                  #                - ./logs/nginx-error.log:/var/log/nginx/error.log
                - ./public:/usr/share/nginx/html
                depends_on:
                        - php

        php:
                image: php:7.2-fpm
                ports:
                        - 9000:9000
                volumes:
                        - ./public:/usr/share/nginx/html

# mysql:
#        image: bitnami/mariadb:latest
#        ports:
#                - 3306:3306
#        volumes:
#                - ./db-data:/var/lib/mysql:rw
#        environment:
#                - MARIADB_ROOT_PASSWORD=123456
