version: '3.1'

services:

        wordpress:
           image: wordpress:4.7.1-php7.0-fpm
           restart: always
           links:
                   - db
           ports:
                   - 9000:9000
           volumes:
                   - ./wordpress:/var/www/html
           environment:
                   WORDPRESS_DB_NAME: wp-tark
                   WORDPRESS_TABLE_PREFIX: wp_
                   WORDPRESS_DB_HOST: db
                   WORDPRESS_DB_USER: wpuser
                   WORDPRESS_DB_PASSWORD: wppass
                   WORDPRESS_DB_NAME: wpdb
        db:
                image: mariadb
                restart: always
                ports:
                        - 3306:3306
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_DATABASE: wpdb
                        MYSQL_USER: wpuser
                        MYSQL_PASSWORD: wppass
                volumes:
                        - ./db:/var/lib/mysql
        nginx:
                image: nginx
                restart: always
                links:
                        - wordpress
                ports:
                        - 80:80
                volumes:
                        - ./nginx:/etc/nginx/conf.d
                        - ./logs/nginx:/var/log/nginx
                        - ./wordpress:/var/www/html
